### ISSUE TITLE
CPU Serial empty. Could not start connection. Timeout.

### ISSUE THREAD

**Issue by qtang** [sdr-enthusiasts/docker-radarbox#130]
**Issue:** "CPU Serial empty." and "Could not start connection. Timeout." errors using RBFeeder Version 1.0.7 (build 20221027145800) via ghcr.io/sdr-enthusiasts/docker-radarbox:latest and mikenye/radarbox:latest images.

The log entries refer to https://github.com/mikenye/docker-radarbox/blob/master/README.md#workaround-for-cpu-serial, but there is no workaround on that page. However, I have copied cpuinfo into fake_cpuinfo, generated a serial number, added the serial number to the end of fake_cpuinfo, and mapped the fake_cpuinfo volume in the rbfeeder container. I am able to see my serial number when running "cat /proc/cpuinfo" from inside the container.

**Workaround:** Reverting to RBFeeder Version 0.4.3 (build 20210909231001) (image: mikenye/radarbox:0.4.3-20210909231001) fixes issue.

docker logs -f  rbfeeder
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-libsecomp2: executing...
[cont-init.d] 00-libsecomp2: exited 0.
[cont-init.d] 01-rbfeeder: executing...
[cont-init.d] 01-rbfeeder: exited 0.
[cont-init.d] done.
[services.d] starting services
[978json-splitter] 2022/12/08 08:24:11 socat[266] W ioctl(5, IOCTL_VM_SOCKETS_GET_LOCAL_CID, ...): Inappropriate ioctl for device
[978json-splitter] 2022/12/08 08:24:11 socat[266] N listening on AF=2 0.0.0.0:30979
[services.d] done.
[rbfeeder] 2022/12/08 08:24:11 [2022-12-08 08:24:11]  Starting RBFeeder Version 1.0.7 (build 20221027145800)
[rbfeeder] 2022/12/08 08:24:11 [2022-12-08 08:24:11]  Using configuration file: /etc/rbfeeder.ini
[rbfeeder] 2022/12/08 08:24:11 [2022-12-08 08:24:11]  Network-mode enabled.
[rbfeeder] 2022/12/08 08:24:11 [2022-12-08 08:24:11]  		Remote host to fetch data: 172.18.0.9
[rbfeeder] 2022/12/08 08:24:11 [2022-12-08 08:24:11]  		Remote port: 30005
[rbfeeder] 2022/12/08 08:24:11 [2022-12-08 08:24:11]  		Remote protocol: BEAST
[rbfeeder] 2022/12/08 08:24:11 [2022-12-08 08:24:11]  Using GNSS (when available)
[rbfeeder] 2022/12/08 08:24:11 [2022-12-08 08:24:11]  Start date/time: 2022-12-08 08:24:11
[rbfeeder] 2022/12/08 08:24:11 [2022-12-08 08:24:11]  Socket for ANRB created. Waiting for connections on port 32088
[rbfeeder] 2022/12/08 08:24:13 [2022-12-08 08:24:13]  Connection established.
[rbfeeder] 2022/12/08 08:24:13 [2022-12-08 08:24:13]  CPU Serial empty.
[rbfeeder] 2022/12/08 08:24:13 [2022-12-08 08:24:13]  Could not start connection. Timeout.
[978json-splitter] 2022/12/08 08:24:14 socat[266] N accepting connection from AF=2 127.0.0.1:48976 on AF=2 127.0.0.1:30979
[978json-splitter] 2022/12/08 08:24:14 socat[266] N forked off child process 296
[978json-splitter] 2022/12/08 08:24:14 socat[266] N listening on AF=2 0.0.0.0:30979
[978json-splitter] 2022/12/08 08:24:14 socat[296] N opening connection to AF=2 172.18.0.7:30979
[978json-splitter] 2022/12/08 08:24:14 socat[296] N successfully connected from local address AF=2 172.18.0.13:53614
[978json-splitter] 2022/12/08 08:24:14 socat[296] N starting data transfer loop with FDs [6,6] and [5,5]

************ ATTENTION! ************

In order to fix the 'CPU Serial empty' issue you are experiencing,
please see: https://github.com/mikenye/docker-radarbox/blob/master/README.md#workaround-for-cpu-serial

************************************

[rbfeeder] 2022/12/08 08:25:11 [2022-12-08 08:25:11]  ******** Statistics updated every 60 seconds ********
[rbfeeder] 2022/12/08 08:25:11 [2022-12-08 08:25:11]  Packets sent in the last 60 seconds: 0, Total packets sent since startup: 0
[rbfeeder] 2022/12/08 08:25:13 [2022-12-08 08:25:13]  Connection established.
[rbfeeder] 2022/12/08 08:25:13 [2022-12-08 08:25:13]  CPU Serial empty.
[rbfeeder] 2022/12/08 08:25:13 [2022-12-08 08:25:13]  Could not start connection. Timeout.
```

Relevant part of compose file:
```
### RadarBox ###
  rbfeeder:
    image: ghcr.io/sdr-enthusiasts/docker-radarbox:latest
#    image: mikenye/radarbox:latest
#    image: mikenye/radarbox:0.4.3-20210909231001
    tty: true
    container_name: rbfeeder
    restart: always
    depends_on:
      - readsb
    environment:
      - BEASTHOST=readsb
      - LAT=${FEEDER_LAT}
      - LONG=${FEEDER_LONG}
      - ALT=${FEEDER_ALT_M}
      - TZ=${FEEDER_TZ}
      - SHARING_KEY=${RADARBOX_SHARING_KEY}
      - UAT_RECEIVER_HOST=dump978
    volumes:
      - '/home/quoc/adsb/data/fake_cpuinfo:/proc/cpuinfo'
    tmpfs:
      - /run:exec,size=64M
      - /var/log
```

Environment:
- Rock64
- Armbian 22.11 Jammy CLI
- Docker version 20.10.21, build baeda1f
- Docker Compose version v2.12.2
- Other services successfully running on same host: readsb, dump978, adsbx, piaware, fr24, pfclient, adsbhub, opensky, tar1090, autoheal, watchtower, lighttpd.
