### ISSUE TITLE
Could not resolve host name specified in 'external_host'.

### ISSUE THREAD

**Issue by Freekers** [sdr-enthusiasts/docker-radarbox#170]
The ```latest``` image got updated last night and since then my rbfeeder is not working anymore. The logs are full with the following error messages:
```
[rbfeeder] getaddrinfo: Name or service not known
[rbfeeder] [2023-03-24 10:40:59]  Could not resolve host name specified in 'external_host'.
[rbfeeder] getaddrinfo: Name or service not known
[rbfeeder] [2023-03-24 10:41:00]  Could not resolve host name specified in 'external_host'.
[rbfeeder] getaddrinfo: Name or service not known
```
This used to work fine before the last update. I think this commit might be related: https://github.com/sdr-enthusiasts/docker-radarbox/commit/965f76b329b938cc21eaeb07953790f32b74875f

For reference, here is my docker compose:

```
  rbfeeder:
    image: ghcr.io/sdr-enthusiasts/docker-radarbox:latest
    container_name: rbfeeder
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - BEASTHOST=192.168.30.224
      - LAT=<REDACTED>
      - LONG=<REDACTED>
      - ALT=25
      - SHARING_KEY=<REDACTED>
      - ENABLE_MLAT=false
   ```

Thanks
